### ISSUE TITLE
The app tries to turn down my keyboard light instead

### ISSUE THREAD

**Issue by limacv** [MrSimonC/Toggle-Mac-Function-Keys#14]
Hello! Thank you for sharing this helpful script! I'm using Macbook Air M2 with the latest Sonoma 14.1.1. When I successfully installed the script as app and run, it seems to click the wrong button that turns down my keyboard light instead. I suspect that the problem lies in:
```
# "Keyboard Shortcuts..." Button
set keyboardButton to 1
click button keyboardButton of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window 1
```
Where the `keyboardButton` refers to a wrong button. However, I'm not familiar with the grammar of the apple script. So it would be great if you could elaborate a little more on what's `keyboardButton` and potential ways to fix the script. Thanks!

**Comment by MrSimonC** [comment]
Hello! Thanks so much for writing in, and glad you found the script useful.

You're not the first person to come across this issue so I've looked into the code history and can you try something for me?

In the section of the script you posted, try to change the `1` to a `3` - as in the code below?

```
# "Keyboard Shortcuts..." Button
set keyboardButton to 3
```

… Try that for me and write back. If it works, then I'll make a comment in the code as you're the third person to write about this! Thanks.

**Comment by limacv** [comment]
After replacing `1` to `3` as suggested the script seems to function properly. Thank you for your help!

**Comment by cartesian-plane** [comment]
I had the same issue on an M1 Air running Sonoma 14.0.
Changing the value from ```1``` to ```3``` fixes it.

**Comment by MrSimonC** [comment]
I've now updated the script to actually try button 3 (in a try/catch) then button 1, so no-one else should ever have this problem again. (And thanks to @cartesian-plane this might even go away entirely with v14 thanks to new `reveal anchor` code which I'd not seen before). Closing.
