### ISSUE TITLE
Error Code "... assistive access. (-25211)"

### ISSUE THREAD

**Issue by arhonallee** [MrSimonC/Toggle-Mac-Function-Keys#17]
The script is working 100% fine for me within the script editor but as soon as I export it as an app, I get the following error message:

ToggleFnKeysOnOff is not allowed assistive access.
System Events got an error:
ToggleFnKeysOnOff is not allowed assistive access. (-25211)

And I have given it permission in Privacy / Accessibility
I also tried various options of exporting it as a new app, tuning assistive access on off again, removing and adding it again, did several reboots and still receive this error message when I am running it as an app. Once again, no problem from within Script director. Ah and when I try to run the script within Shortcuts, I get the same error message with the difference that Shortcut would not have permission for assistive access which it does of course.

Anyone came across the same problem with other scripts that have been exported as an app? Solution ideas?

**Comment by MrSimonC** [comment]
Apologies - I've only just seen this issue even though you logged it two days ago. I've just retried and I've recreated the same problem as you. The difference for me is that I get the same error message if I don't have Shortcuts itself allowed to be used for Accessibility. So, for example, I get the exact same error message as you, until I follow these steps...

System Preferences, Security & Privacy, Accessibility, you'll see Shortcuts as Off:
<img width="448" alt="Screenshot 2024-05-27 at 21 56 45" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/38e83025-7ae1-4e65-b05d-f9d4170c1466">
so switch it to On:
<img width="694" alt="Screenshot 2024-05-27 at 21 58 00" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/0eafe0e8-0a10-406e-9cdb-8106a6a3103e">

... which solves the problem for me.

**Comment by arhonallee** [comment]
<img width="658" alt="Screenshot 2024-05-28 at 16 58 25" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/170851279/dad05323-fe94-486b-a44f-5ce65ddc2a03">
Thanks for your reply, to be honest I am giving up at this point. I just cannot get rid of the permission error. Everything is toggled on as allowed under Privacy & Security / Accessibility and at this point I tried it from any direction I could think of.
But thanks anyway for writing the script, maybe with the next macOS version the situation is looking better than🙌

**Comment by MrSimonC** [comment]
Thanks for replying back @arhonallee - sorry it didn't work out. One day let's hope we all get a command-line hook we can all use and retire all this AppleScript workaround!
