### ISSUE TITLE
System Settings got an error: AppleEvent handler failed.

### ISSUE THREAD

**Issue by sunrisewestern** [MrSimonC/Toggle-Mac-Function-Keys#2]
on Macos 13.0.1

System Settings got an error: AppleEvent handler failed. 

Seems because they change the layout of system preference.

**Comment by MrSimonC** [comment]
Thanks for letting me know, I'll get right on it.

**Comment by MrSimonC** [comment]
Hello @sunrisewestern this has been fixed now - please update [the script again](https://github.com/MrSimonC/Toggle-Mac-Function-Keys/blob/main/Toggle%20Function%20Keys.scpt) and it should work. I've tested it myself on MacOS Ventura (on MacBook Air with no Touch Bar)
