### ISSUE TITLE
Running the app at boot

### ISSUE THREAD

**Issue by SoftTransistor** [MrSimonC/Toggle-Mac-Function-Keys#3]
Hello, 

Just a small idea on how to run the app. I set it has a startup program of the OS in the preference : 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/43668745/226388624-8545ccb9-e9d5-48c7-a6c3-86e0880697d6.png">

I found it easier to put that as an issue, but remove it if you want.

Thank you for the script :)

**Comment by MrSimonC** [comment]
Hello @SoftTransistor!
Thanks for creating an issue and for the tip. I've updated the [main page](https://github.com/MrSimonC/Toggle-Mac-Function-Keys) with your tip and a credit to you as well. Thanks so much! Glad the script helps!

Kind regards,
Simon
