### ISSUE TITLE
Hello, does this script support non-apple keyboards ?

### ISSUE THREAD

**Issue by Gui052** [MrSimonC/Toggle-Mac-Function-Keys#7]

**Comment by MrSimonC** [comment]
Hello! Thank you for your question.

I will try to answer it with the most accuracy I can come up with, which is that if you going to the Apple System Settings and see this screen:
<img width="717" alt="Screenshot 2023-06-20 at 10 36 49" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/373c79f5-ceb8-4d81-b973-134d8bcd8d5a">
then click Keyboard Shortcuts, and see this screen:
<img width="659" alt="Screenshot 2023-06-20 at 10 38 00" src="https://github.com/MrSimonC/Toggle-Mac-Function-Keys/assets/3033044/a121266a-a1c5-46c0-92c2-4ea4e63ea326">
... then the script will work.

Whether you see these screens actually depends on which keyboard you have pulled in. For example, apple keyboards with a touchbar will actually float an extra button which confuses the script.

Hope that helps!
