### ISSUE TITLE
Suggestions to run the script in the background without opening the UI

### ISSUE THREAD

**Issue by hdecoded** [MrSimonC/Toggle-Mac-Function-Keys#8]
Hi,

I am running the script using Raycast but I want it to run in the background without opening any UI. Is that possible? 

Can you please point me in the right direction.

**Comment by MrSimonC** [comment]
Hi! That's really tricky. I've looked into other CLI scripts in the past, but they tend to break / they work until you have to reboot etc. This (painful) AppleScript only works by awkwardly using the UI - so what you're asking for is *kinda* possible, but not using AppleScript (that I know of)... for me, I trigger this script, then just wait a few seconds and the UI does it's thing, then closes ... which is good enough for me.

If you do find a solution - do let me know. good luck! 👍🏻
